language: scala
before_script:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - sudo /etc/init.d/rethinkdb start
scala:
  - 2.10.4
jdk:
  - oraclejdk7
  - openjdk6

script: sbt ++$TRAVIS_SCALA_VERSION test
